Rental_management_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from signup.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('equipment/',include('equipment.urls','equipment')),
    path('rental/', include('rental.urls', 'rental')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('signin/', register, name='signin')
]

django_rental_management/django_rental_management/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

equipment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import ListView

from equipment import views
from . views import *
from .models import Equipment, Vendor, Category

app_name= 'equipment'
urlpatterns = [
    path('', views.index),

    # path('equipment/', ListView.as_view(
    # queryset = Equipment.objects.all(),
    # template_name='equipment/equipment_list.html',
    # context_object_name = 'total_equipment_list'
    # ), name='equipment_list'),
    path('equipment/', EquipmentList.as_view(), name='equipment_list'),
    path('equipment/<int:pk>/',EquipmentDetail.as_view(), name='equipment_detail'),
    path('equipment/create/', EquipmentCreate.as_view(), name='equipment_create'),
    path('equipment/<int:pk>/edit/',EquipmentUpdate.as_view(), name='equipment_update'),
    path('equipment/<int:pk>/delete/',EquipmentDelete.as_view(), name='equipment_confirm_delete'),

    path('vendor/', VendorList.as_view(), name='vendor_list'),
    path('vendor/<int:pk>/',VendorDetail.as_view(), name='vendor_detail'),
    path('vendor/create/', VendorCreate.as_view(), name='vendor_create'),
    path('vendor/<int:pk>/edit/',VendorUpdate.as_view(), name='vendor_update'),
    path('vendor/<int:pk>/delete/',VendorDelete.as_view(), name='vendor_confirm_delete'),

    path('category/', CategoryList.as_view(), name='category_list'),
    path('category/<int:pk>/',CategoryDetail.as_view(), name='category_detail'),
    path('category/create/', CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/edit/',CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/',CategoryDelete.as_view(), name='category_confirm_delete'),



]

rental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import ListView

from rental import views
from . views import *
from .models import *

app_name='rental'
urlpatterns = [
    path('', views.index),

    path('rental/', RentalList.as_view(), name='rental_list'),
    path('rental/<int:pk>/', RentalDetail.as_view(), name='rental_detail'),
    path('rental/create/', RentalCreate.as_view(), name='rental_create'),
    path('rental/<int:pk>/edit/', RentalUpdate.as_view(), name='rental_update'),
    path('rental/<int:pk>/delete/', RentalDelete.as_view(), name='rental_confirm_delete'),

    # path('job/', ListView.as_view(
    #     queryset=Job.objects.all(),
    #     template_name='job/job_list.html',
    #     context_object_name='job_list'
    # ), name='job_list'),
    path('job/', JobList.as_view(), name='job_list'),
    path('job/<int:pk>/', JobDetail.as_view(), name='job_detail'),
    path('job/create/', JobCreate.as_view(), name='job_create'),
    path('job/<int:pk>/edit/', JobUpdate.as_view(), name='job_update'),
    path('job/<int:pk>/delete/', JobDelete.as_view(), name='job_confirm_delete'),
]

equipment/models.py
from django.db import models

# Create your models here.



class Equipment(models.Model):
    category = models.ForeignKey('Category', related_name='equipments',on_delete = models.SET_NULL, null=True)
    vendor = models.ForeignKey('Vendor', related_name='equipments', on_delete = models.SET_NULL, null=True)
    name = models.CharField(max_length = 50)
    serial_number = models.CharField(max_length = 6, unique=True)
    available = models.BooleanField(default = True)
    day_rate = models.FloatField(default = 0)
    week_rate = models.FloatField(default = 0)
    month_rate = models.FloatField(default = 0)
    retail_price = models.FloatField(default = 0)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return u'/equipment/category/%d' % self.id



class Category(models.Model):
    name = models.CharField(max_length = 100, unique = True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return u'/equipment/category/%d' % self.id

class Vendor(models.Model):
    name = models.CharField(max_length = 20, unique=True)
    address = models.TextField()
    email = models.EmailField()
    phone = models.CharField(max_length = 11)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return u'/equipment/vendor/%d' % self.id

equipment/forms.py
from django.forms import ModelForm
from .models import Equipment, Category, Vendor

class EquipmentForm(ModelForm):
    class Meta:
        model = Equipment
        fields = [
        'category',
        'vendor',
        'name',
        'serial_number',
        'available',
        'day_rate',
        'week_rate',
        'month_rate',
        'retail_price'
        ]
        localize = True

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']

class VendorForm(ModelForm):
    class Meta:
        model = Vendor
        fields= [
        'name',
        'address',
        'email',
        'phone'
        ]

equipment/views.py
from django.shortcuts import render
from .models import *
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.contrib.auth.decorators import permission_required, login_required
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import *

@login_required
def index(request):
    return render(request, 'EquipmentNavigate.html')

class EquipmentDetail(LoginRequiredMixin, DetailView):
    permission_denied_message = 'You must log in first'
    model = Equipment
    template_name = 'equipment/equipment_detail.html'

    def get_context_data(self, **kwargs):
        context = super(EquipmentDetail, self).get_context_data(**kwargs)
        return context


class EquipmentCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'equipment.add_equipment'
    permission_denied_message = "You are not allowed to create a new equipment"
    model = Equipment
    template_name = 'equipment/forms.html'
    form_class = EquipmentForm

    success_url= '/equipment/equipment'
    def form_valid(self, form):

        return super(EquipmentCreate, self).form_valid(form)


class EquipmentUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'equipment.change_equipment'
    permission_denied_message = "You are not allowed to update a new equipment"
    model = Equipment
    template_name = 'equipment/forms.html'
    fields = [
    'category',
    'vendor',
    'available',
    'day_rate',
    'week_rate',
    'month_rate',
    'retail_price'
    ]
    help_text= "Equipment"

    success_url= '/equipment/equipment'

class EquipmentList(LoginRequiredMixin, ListView):
    queryset = Equipment.objects.all()
    template_name='equipment/equipment_list.html'
    context_object_name = 'total_equipment_list'

class EquipmentDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'equipment.delete_equipment'
    permission_denied_message = 'You cannot delete equipment'
    model = Equipment
    success_url = '../'

class VendorList(LoginRequiredMixin, ListView):
    queryset = Vendor.objects.all()
    template_name='vendor/vendor_list.html'
    context_object_name = 'total_vendor_list'

class VendorDetail(LoginRequiredMixin, DetailView):
    permission_denied_message = 'You must login first'
    model = Vendor
    template_name = 'vendor/vendor_detail.html'

    def get_context_data(self, **kwargs):
        context = super(VendorDetail, self).get_context_data(**kwargs)
        return context

class VendorCreate(PermissionRequiredMixin, CreateView):
    permission_denied_message = 'You cannot create a new vendor'
    permission_required = 'equipment.add_vendor'
    model = Vendor
    template_name = 'equipment/forms.html'
    form_class = VendorForm

    success_url= '/equipment/vendor'
    def form_valid(self, form):

        return super(VendorCreate, self).form_valid(form)

class VendorUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'equipment.change_vendor'
    permission_denied_message = 'You cannot update vendor'
    model = Vendor
    template_name = 'equipment/forms.html'
    fields = [
    'name',
    'address',
    'email',
    'phone',
    ]
    success_url= '/equipment/vendor'


class VendorDelete(PermissionRequiredMixin, DeleteView):
    permission_denied_message = 'You cannot delete vendor information'
    permission_required = 'equipment.delete_vendor'
    model = Vendor
    success_url = '../'

class CategoryList(LoginRequiredMixin, ListView):
    queryset = Category.objects.all()
    template_name='category/category_list.html'
    context_object_name = 'total_category_list'


class CategoryDetail(LoginRequiredMixin, DetailView):
    permission_denied_message = 'You must login first'
    model = Category
    template_name = 'category/category_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryDetail, self).get_context_data(**kwargs)
        return context

class CategoryCreate(PermissionRequiredMixin, CreateView):
    permission_denied_message = 'You are not allowed to create a category'
    permission_required = 'equipment.add_category'
    model = Category
    template_name = 'equipment/forms.html'
    form_class = CategoryForm

    success_url= '/equipment/category'
    def form_valid(self, form):

        return super(CategoryCreate, self).form_valid(form)

class CategoryUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'equipment.change_category'
    permission_denied_message = 'You cannot update a category'
    model = Category
    template_name = 'equipment/forms.html'
    fields = [
    'name',
    ]
    success_url= '/equipment/category'


class CategoryDelete(PermissionRequiredMixin, DeleteView):
    permission_denied_message = 'You are not allowed to delete a category'
    permission_required = 'equipment.delete_category'
    model = Category
    success_url = '../'

equipment/templates/equipment/category_confirm_delete.html
{% extends 'base.html'%}
    {% block title %}
Delete {{object}}
    {% endblock %}
  {% block content%}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

equipment/templates/equipment/equipment_confirm_delete.html
{% extends 'base.html'%}
{% block title %}
Delete {{object}}
{% endblock %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

equipment/templates/equipment/equipment_detail.html
{% extends 'base.html'%}
    {% block title %}
    {{ equipment.name }} {{ equipment.serial_number }}
    {% endblock %}
    {% block sidebar%}

    {% if user.groups.all.0.name == 'moderator' %}

    <a href="{% url 'equipment:equipment_update' equipment.id%}">Edit {{equipment.id}}</a>
    <a href="{% url 'equipment:equipment_confirm_delete' equipment.id%}">Delete {{equipment.id}}</a>
  {%endif%}
  <a href="{% url 'equipment:equipment_list'%}">Back to Equipments</a>

  {%endblock%}
  {% block content%}
    Info about {{ equipment.name }} :

    <p>Vendor: <a href="{% url 'equipment:vendor_detail' equipment.vendor.id %}">{{equipment.vendor}}</a></p>
      <p>Category: <a href="{% url 'equipment:category_detail' equipment.category.id %}">{{equipment.category}}</a></p>
<p>Serial Number: {{equipment.serial_number}}</p>

<p>Is Available: {{equipment.available}}</p>
<p>Daily Rate: {{equipment.day_rate}}</p>
<p>Weekly Rate: {{equipment.week_rate}}</p>
<p>Month Rate: {{equipment.month_rate}}</p>
<p>Retail Price: {{equipment.retail_price}}</p>

{% endblock%}

equipment/templates/equipment/equipment_list.html
{% extends 'base.html'%}
    {% block title %}
Equipment
    {% endblock %}
    {% block sidebar%}
    {% if user.groups.all.0.name == 'moderator' %}

    <a href="{% url 'equipment:equipment_create'%}">New equipment</a>
{%endif%}
  {% endblock%}
  {% block content%}

    {%for item in total_equipment_list %}
    <ul>
      <li><a href="{% url 'equipment:equipment_detail' item.id %}">{{item.name}}</a></li>
    </ul>

    {% endfor %}
{% endblock %}

equipment/templates/equipment/forms.html
{% extends 'base.html'%}
    {% block title %}
    {{form.help_text}}
    {% endblock %}
  {% block content%}

<form method="post" enctype="multipart/form-data" action="">
    {% csrf_token %}
    <table>
        {{ form.as_p }}
    </table>
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

equipment/templates/equipment/vendor_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>